export * from './example/ExampleRepository';
export * from '../../../email/domain/repository/EmailRepository';
export * from './people/PeopleRepository';
export * from './country/CountryRepository';
export * from './people-status/PeopleStatusRepository';
export * from './user/UserRepository'
export * from './auth-service/AuthServiceRepository';
export * from './people-country/PeopleCountryRepository';
export * from './address/AddressRepository';