export enum HttpStatusCode {
    //Success
    HTTP_OK = 200,
    HTTP_CREATED = 201,

    //Client errors
    HTTP_BAD_REQUEST = 400,
    HTTP_UNAUTHORIZED = 401,
    HTTP_FORBIDEN = 403,
    HTTP_NOT_FOUND = 404,
    HTTP_UNPROCESABLE_ENTITY = 422,
    HTTP_TO_MANY_REQUESTS = 429,
    HTTP_UNSOPPORTED_MEDIA_TYPE = 415,
    HTTP_METHOD_NOT_ALLOWED = 405,
    
    // Server errors
    HTTP_INTERNAL_SERVER_ERROR = 500
}