export * from './example/example.entity';
export * from './user/user.entity';
export * from './permission/permission.entity';
export * from './rol/rol.entity';
export * from './status-rol/status.rol.entity';
export * from './status-user/status.user.entity';
export * from './user-rol/user.rol.entity';
export * from './rol-permission/rol.permission.entity'
export * from '../../../profile/domain/entities/marital-status/Marital.Status.Entity';