export * from './example/example.entity';
export * from './user/user.entity';
export * from './people/people.entity';
export * from './permission/permission.entity';
export * from './rol/rol.entity';
export * from './status-rol/status.rol.entity';
export * from './status-user/status.user.entity';
export * from './user-rol/user.rol.entity';
export * from './insurance/insurance.entity';
export * from './rol-permission/rol.permission.entity'
export * from './type-insurance/type.insurance.entity';
export * from './document-people/document.people.entity';
export * from './country/coutnry.entity';
export * from './municipality/municipality.entity';
export * from './district/district.entity';
export * from './department/department.entity';
